name: Content Sync to EC2
on:
  push:
    branches: [ main ]
    paths: [ 'src/main/resources/docs/**/**.md' ]   # md 변경에만 반응

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 and sync repo
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }} # Scale-Out 환경에서는 무리가 있음 SSM 방식으로 전환 필요
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e 
            cd /opt/cs-contents/cs-study-contents
            git fetch --prune origin
            git checkout main
            old=$(git rev-parse HEAD)
            git reset --hard origin/main
            new=$(git rev-parse HEAD)
            echo "Updated $old -> $new"